# Generated by Django 5.0.6 on 2024-06-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='adress',
            new_name='address',
        ),
    ]
